<div class="controls">
    <?= $tabs->showOnlyCloseButton() ?>
</div>
<div class="content">
  <table class="avp" style="width: <?= intval(urldecode($this->graph_width)) ?>px; text-align: center;">
    <tr>
      <td><a target="graph_iframe" class="icon-clock" href="<?= urldecode($this->url) ?>&from=-10min">10 minutes</a></td>
      <td><a target="graph_iframe" class="icon-clock" href="<?= urldecode($this->url) ?>&from=-1h">1 hour</a></td>
      <td><a target="graph_iframe" class="icon-clock" href="<?= urldecode($this->url) ?>&from=-12h">12 hours</a></td>
      <td><a target="graph_iframe" class="icon-clock" href="<?= urldecode($this->url) ?>&from=-1d">1 day</a></td>
      <td><a target="graph_iframe" class="icon-clock" href="<?= urldecode($this->url) ?>&from=-1w">1 week</a></td>
      <td><a target="graph_iframe" class="icon-clock" href="<?= urldecode($this->url) ?>&from=-1mon">1 month</a></td>
      <td><a target="graph_iframe" class="icon-clock" href="<?= urldecode($this->url) ?>&from=-1y">1 year</a></td>
    </tr>
  </table>
  <iframe name ="graph_iframe" src="<?= urldecode($this->url) ?>" style="height: <?= intval(urldecode($this->graph_height)) ?>px; width: <?= intval(urldecode($this->graph_width)) ?>px" frameborder="no"></iframe>
</div>
